### PR TITLE
Fix deprecated warning

### PR DESCRIPTION
**Pull request by aditijms**

### CODE REVIEW

**Comment by aditijms** [comment]
cc @schaffererin

**Comment by schaffererin** [comment]
@aditijms - looks good for sign off.

**Comment by aditijms** [comment]
@schaffererin, looks like I can't merge, though.

**Comment by aditijms** [comment]
Hi @zr-msft, is this something that you could merge? Thanks!

**Comment by zr-msft** [comment]
Sorry for the delay @aditijms and thank you for the fix

This was addressed in #63

Closing

**Pull request closed without merging**
